
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/bazzite/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Linux - 6.17.7-ba01.fc43.x86_64 - x86_64
...
